version: '2'
services:
    web:
        build: .
        ports:
            - "5003:5003"
            - "5006:5006"
            - "5055:5055"
        depends_on:
            - redis
        restart: always
    redis:
        image: redis
        restart: always
